DEFINE CURRENT_YEAR  = EXTRACT(YEAR FROM sysdate);

SELECT
    COUNT(*) as ctr,
    ROUND( COUNT(*) * 100.0 / SUM(COUNT(*)) over(), 2) as percentage_score,
    CASE
    WHEN &CURRENT_YEAR - t.MEMBER_BIRTH_YEAR BETWEEN 0 AND 18 THEN '<18'
    WHEN &CURRENT_YEAR - t.MEMBER_BIRTH_YEAR BETWEEN 18 AND 24 THEN '18 - 24'
    WHEN &CURRENT_YEAR - t.MEMBER_BIRTH_YEAR BETWEEN 24 AND 35 THEN '24 - 35'
    WHEN &CURRENT_YEAR - t.MEMBER_BIRTH_YEAR BETWEEN 35 AND 50 THEN '35 - 50'
    ELSE '>50'
    END INTERVAL
FROM TRIPS t WHERE t.MEMBER_BIRTH_YEAR IS NOT NULL
GROUP BY
    CASE
    WHEN &CURRENT_YEAR - t.MEMBER_BIRTH_YEAR BETWEEN 0 AND 18 THEN '<18'
    WHEN &CURRENT_YEAR - t.MEMBER_BIRTH_YEAR BETWEEN 18 AND 24 THEN '18 - 24'
    WHEN &CURRENT_YEAR - t.MEMBER_BIRTH_YEAR BETWEEN 24 AND 35 THEN '24 - 35'
    WHEN &CURRENT_YEAR - t.MEMBER_BIRTH_YEAR BETWEEN 35 AND 50 THEN '35 - 50'
    ELSE '>50'
    END 
ORDER BY 3


