SELECT
S_TRIP_ID AS CURRENT_TRIP_ID,
S_STATION_ID,
S_NAME AS START_STATION_NAME,
S_END_STATION_ID,
E_NAME AS END_STATION_NAME,
S_START_DATE AS CURRENT_TRIP_START_DATE,
S_END_DATE AS CURRENT_TRIP_END_DATE,
TRIP_ID_BEFORE,
pierwsza.BEFORE_START_DATE AS BEFORE_TRIP_START_DATE,
BEFORE_END_DATE AS BEFORE_TRIP_END_DATE,
E_B_NAME AS BEFORE_TRIP_END_STATION

FROM(

(SELECT zad.S_STATION_ID, zad.S_NAME, zad.S_REGION_NAME, zad.S_END_STATION_ID, zad.E_NAME, zad.S_TRIP_ID, zad.S_START_DATE, zad.S_END_DATE,part.TRIP_ID_BEFORE,
part.BEFORE_START_DATE,  part.BEFORE_END_DATE, part.E_B_NAME
FROM(
(SELECT * FROM(
(SELECT STATION_ID as S_STATION_ID, s.NAME as S_NAME, r.name as S_REGION_NAME, END_STATION_ID as S_END_STATION_ID, t.TRIP_ID as S_TRIP_ID,  t.start_date as S_START_DATE , t.end_date S_END_DATE
FROM ((STATION_INFO s
INNER JOIN REGIONS r ON s.REGION_ID = r.REGION_ID)
INNER JOIN TRIPS t ON t.START_STATION_ID= s.STATION_ID)) j
INNER JOIN 
(SELECT  DISTINCT(STATION_ID) as E_STATION_ID, s.NAME as E_NAME
FROM ((STATION_INFO s
INNER JOIN REGIONS r ON s.REGION_ID = r.REGION_ID)
INNER JOIN TRIPS t ON t.END_STATION_ID= s.STATION_ID)) p
ON j.S_END_STATION_ID = p.e_station_id)
WHERE UPPER(S_REGION_NAME) like 'SAN FRANCISCO') zad

INNER JOIN

(SELECT * FROM(
(SELECT STATION_ID as S_STATION_ID, s.NAME as S_NAME, r.name as S_REGION_NAME, END_STATION_ID,  t.TRIP_ID as TRIP_ID_BEFORE,  t.start_date AS BEFORE_START_DATE , t.end_date AS BEFORE_END_DATE
FROM ((STATION_INFO s
INNER JOIN REGIONS r ON s.REGION_ID = r.REGION_ID)
INNER JOIN TRIPS t ON t.START_STATION_ID= s.STATION_ID)) j
INNER JOIN 
(SELECT  DISTINCT(STATION_ID) as E_STATION_ID, s.NAME as E_B_NAME
FROM ((STATION_INFO s
INNER JOIN REGIONS r ON s.REGION_ID = r.REGION_ID)
INNER JOIN TRIPS t ON t.END_STATION_ID= s.STATION_ID)) p
ON j.END_STATION_ID = p.e_station_id)) part
ON part.S_NAME = zad.S_NAME
AND zad.S_START_DATE > part.BEFORE_START_DATE)) pierwsza

INNER JOIN

(SELECT TRIP_ID, max(BEFORE_START_DATE) as BEFORE_START_DATE FROM(
(SELECT * FROM(
(SELECT STATION_ID as S_STATION_ID, s.NAME as S_NAME, r.name as S_REGION_NAME, END_STATION_ID, t.TRIP_ID,  t.start_date , t.end_date
FROM ((STATION_INFO s
INNER JOIN REGIONS r ON s.REGION_ID = r.REGION_ID)
INNER JOIN TRIPS t ON t.START_STATION_ID= s.STATION_ID)) j
INNER JOIN 
(SELECT  DISTINCT(STATION_ID) as E_STATION_ID, s.NAME as E_NAME
FROM ((STATION_INFO s
INNER JOIN REGIONS r ON s.REGION_ID = r.REGION_ID)
INNER JOIN TRIPS t ON t.END_STATION_ID= s.STATION_ID)) p
ON j.END_STATION_ID = p.e_station_id)
where upper(S_REGION_NAME) like 'SAN FRANCISCO') zad

INNER JOIN

(SELECT * FROM(
(SELECT STATION_ID as S_STATION_ID, s.NAME as S_NAME, r.name as S_REGION_NAME, END_STATION_ID, t.TRIP_ID as TRIP_ID_BEFORE,  t.start_date AS BEFORE_START_DATE , t.end_date AS BEFORE_END_DATE
FROM ((STATION_INFO s
INNER JOIN REGIONS r ON s.REGION_ID = r.REGION_ID)
INNER JOIN TRIPS t ON t.START_STATION_ID= s.STATION_ID)) j
INNER JOIN 
(SELECT  DISTINCT(STATION_ID) as E_STATION_ID, s.NAME as E_NAME
FROM ((STATION_INFO s
INNER JOIN REGIONS r ON s.REGION_ID = r.REGION_ID)
INNER JOIN TRIPS t ON t.END_STATION_ID= s.STATION_ID)) p
ON j.END_STATION_ID = p.e_station_id)) part
ON part.S_NAME = zad.S_NAME
AND zad.START_DATE > part.BEFORE_START_DATE
)GROUP BY TRIP_ID) druga


ON
pierwsza.S_TRIP_ID = druga.trip_id
AND
pierwsza.before_start_date = druga.before_start_date
)
ORDER BY S_STATION_ID

